/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:bdd99673-18f6-43d9-af96-267303abf511",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_f6R8Pt1g8",
    "aws_user_pools_web_client_id": "7hut23qtq1kq3hpd6k1bpmlcr",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://im4xwt2u7zfuxpenyjzr6eucma.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
